// env-manager: procrastimate | 2026-10-08T13:16:37.298Z
// env-manager target: app-web
// env-manager root: ..
// env-manager env: local
// AUTO-GENERATED by `env-manager generate` - do not edit
import { z } from 'zod';

const env = z.object({
  API_URL: z.url(),
  CLIENT_PORT: z.coerce.number().int().min(1).max(65535),
  CLIENT_HOST: z.string().optional(),
}).parse(process.env);

export default env;
