// Generated by scripts/tokens.ts from app-web/src/index.css. Do not edit; run `bun scripts/tokens.ts`.
import SwiftUI

/// The web's semantic color tokens, one light and one dark value each.
enum Palette {
    static let accent = Color(light: SRGB(0xBF3820), dark: SRGB(0xFF7A61))
    static let onAccent = Color(light: SRGB(0xFFFFFF), dark: SRGB(0x1C0A06))
    static let ink = Color(light: SRGB(0x18181B), dark: SRGB(0xECECEF))
    static let muted = Color(light: SRGB(0x56565F), dark: SRGB(0xA8A8B1))
    static let faint = Color(light: SRGB(0x67676F), dark: SRGB(0x96969F))
    static let surface = Color(light: SRGB(0xFFFFFF), dark: SRGB(0x3A3A41))
    static let scrim = Color(light: SRGB(0x18181B, 0.12), dark: SRGB(0x000000, 0.45))
    static let canvas = Color(light: SRGB(0xF6F6F7), dark: SRGB(0x0E0E10))
    static let canvasGlowWarm = Color(light: SRGB(0xFFE4D6, 0.6), dark: SRGB(0xE8492F, 0.11))
    static let canvasGlowCool = Color(light: SRGB(0xDCE4FF, 0.7), dark: SRGB(0x506EFF, 0.11))
    static let glassBg = Color(light: SRGB(0xFFFFFF, 0.72), dark: SRGB(0x2C2C32, 0.72))
    static let glassStrongBg = Color(light: SRGB(0xFAFAFC, 0.94), dark: SRGB(0x1E1E24, 0.94))
    static let glassSolid = Color(light: SRGB(0xFBFBFC), dark: SRGB(0x26262B))
    static let glassRim = Color(light: SRGB(0xFFFFFF, 0.95), dark: SRGB(0xFFFFFF, 0.2))
    static let glassRimLow = Color(light: SRGB(0xFFFFFF, 0.45), dark: SRGB(0xFFFFFF, 0.06))
    static let glassEdge = Color(light: SRGB(0x18181B, 0.07), dark: SRGB(0xFFFFFF, 0.07))
    static let fillControl = Color(light: SRGB(0xFFFFFF, 0.78), dark: SRGB(0xFFFFFF, 0.06))
    static let glassShadow = Color(light: SRGB(0x18181B, 0.16), dark: SRGB(0x000000, 0.55))
    static let glassShadowStrong = Color(light: SRGB(0x18181B, 0.26), dark: SRGB(0x000000, 0.7))
    static let p1 = Color(light: SRGB(0xE5484D), dark: SRGB(0xFF6369))
    static let p2 = Color(light: SRGB(0xF2994A), dark: SRGB(0xFFA04D))
    static let p3 = Color(light: SRGB(0x3E7BFA), dark: SRGB(0x6B9BFF))
    static let p4 = Color(light: SRGB(0xA1A1AA), dark: SRGB(0x8B8B94))
    static let toneOverdue = Color(light: SRGB(0xC4262B), dark: SRGB(0xFF7477))
    static let toneToday = Color(light: SRGB(0x127238), dark: SRGB(0x3FCF7C))
    static let toneTomorrow = Color(light: SRGB(0x9E4B06), dark: SRGB(0xF5A524))
    static let toneWeek = Color(light: SRGB(0x6A48E8), dark: SRGB(0xA78BFA))
    static let toneLater = Color(light: SRGB(0x56565F), dark: SRGB(0xA8A8B1))
    static let toneLabel = Color(light: SRGB(0x0F766E), dark: SRGB(0x2DD4BF))
    static let tokenDue = Color(light: SRGB(0x1F9D55, 0.16), dark: SRGB(0x3FCF7C, 0.22))
    static let tokenPriority = Color(light: SRGB(0xE5484D, 0.15), dark: SRGB(0xFF6369, 0.22))
    static let tokenReminder = Color(light: SRGB(0x7C5CFF, 0.16), dark: SRGB(0xA78BFA, 0.24))
    static let tokenProject = Color(light: SRGB(0x3E7BFA, 0.15), dark: SRGB(0x6B9BFF, 0.22))
    static let tokenRecurrence = Color(light: SRGB(0xD97706, 0.16), dark: SRGB(0xF5A524, 0.22))
    static let tokenMatch = Color(light: SRGB(0xFACC15, 0.4), dark: SRGB(0xFACC15, 0.3))
    static let tokenLabel = Color(light: SRGB(0x0D9488, 0.15), dark: SRGB(0x2DD4BF, 0.2))
}

extension ShapeStyle where Self == Color {
    static var accent: Color { Palette.accent }
    static var onAccent: Color { Palette.onAccent }
    static var ink: Color { Palette.ink }
    static var muted: Color { Palette.muted }
    static var faint: Color { Palette.faint }
    static var surface: Color { Palette.surface }
    static var scrim: Color { Palette.scrim }
    static var canvas: Color { Palette.canvas }
    static var canvasGlowWarm: Color { Palette.canvasGlowWarm }
    static var canvasGlowCool: Color { Palette.canvasGlowCool }
    static var glassBg: Color { Palette.glassBg }
    static var glassStrongBg: Color { Palette.glassStrongBg }
    static var glassSolid: Color { Palette.glassSolid }
    static var glassRim: Color { Palette.glassRim }
    static var glassRimLow: Color { Palette.glassRimLow }
    static var glassEdge: Color { Palette.glassEdge }
    static var fillControl: Color { Palette.fillControl }
    static var glassShadow: Color { Palette.glassShadow }
    static var glassShadowStrong: Color { Palette.glassShadowStrong }
    static var p1: Color { Palette.p1 }
    static var p2: Color { Palette.p2 }
    static var p3: Color { Palette.p3 }
    static var p4: Color { Palette.p4 }
    static var toneOverdue: Color { Palette.toneOverdue }
    static var toneToday: Color { Palette.toneToday }
    static var toneTomorrow: Color { Palette.toneTomorrow }
    static var toneWeek: Color { Palette.toneWeek }
    static var toneLater: Color { Palette.toneLater }
    static var toneLabel: Color { Palette.toneLabel }
    static var tokenDue: Color { Palette.tokenDue }
    static var tokenPriority: Color { Palette.tokenPriority }
    static var tokenReminder: Color { Palette.tokenReminder }
    static var tokenProject: Color { Palette.tokenProject }
    static var tokenRecurrence: Color { Palette.tokenRecurrence }
    static var tokenMatch: Color { Palette.tokenMatch }
    static var tokenLabel: Color { Palette.tokenLabel }
}
