#!/usr/bin/env bun
// Generates Sources/App/Theme/Tokens.swift from the web's semantic color tokens in app-web/src/index.css.
// `--check` fails instead of writing when the committed file is stale.
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dir, '..');
const cssPath = resolve(root, '../app-web/src/index.css');
const outPath = resolve(root, 'Sources/App/Theme/Tokens.swift');

type Rgba = [number, number, number, number];
type Tokens = Record<string, string>;

function block(css: string, selector: string): Tokens {
	const start = css.indexOf(`\n${selector} {`);
	if (start < 0) throw new Error(`index.css has no ${selector} block`);
	const body = css.slice(start, css.indexOf('\n}', start));
	return Object.fromEntries(
		[...body.matchAll(/(--[\w-]+):\s*([^;]+);/g)].map(([, name, value]) => [name!, value!.trim()]),
	);
}

function color(tokens: Tokens, value: string): Rgba | undefined {
	const reference = value.match(/^var\((--[\w-]+)\)$/);
	if (reference) {
		const target = tokens[reference[1]!];
		if (target === undefined) throw new Error(`Unknown token ${reference[1]}`);
		return color(tokens, target);
	}
	const hex = value.match(/^#([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$/i);
	if (hex) return [...hex.slice(1, 4).map(h => parseInt(h, 16)), 1] as Rgba;
	const rgb = value.match(/^rgb\((\d+) (\d+) (\d+)(?: \/ ([\d.]+))?\)$/);
	if (rgb) return [Number(rgb[1]), Number(rgb[2]), Number(rgb[3]), rgb[4] ? Number(rgb[4]) : 1];
	return undefined;
}

/** `--color-on-accent` and `--glass-strong-bg` become `onAccent` and `glassStrongBg`. */
const swiftName = (token: string) =>
	token.replace(/^--(color-)?/, '').replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());

const literal = ([r, g, b, a]: Rgba) => {
	const hex = `0x${[r, g, b].map(c => c.toString(16).padStart(2, '0').toUpperCase()).join('')}`;
	return a === 1 ? `SRGB(${hex})` : `SRGB(${hex}, ${a})`;
};

function generate(css: string): string {
	const light = { ...block(css, '@theme'), ...block(css, ':root') };
	const dark = { ...light, ...block(css, ":root[data-theme='dark']") };
	const names = Object.keys(light).filter(name => color(light, light[name]!));
	const lines = names.map(name => {
		const pair = `light: ${literal(color(light, light[name]!)!)}, dark: ${literal(color(dark, dark[name]!)!)}`;
		return `    static let ${swiftName(name)} = Color(${pair})`;
	});
	const styles = names.map(name => `    static var ${swiftName(name)}: Color { Palette.${swiftName(name)} }`);
	return `// Generated by scripts/tokens.ts from app-web/src/index.css. Do not edit; run \`bun scripts/tokens.ts\`.
import SwiftUI

/// The web's semantic color tokens, one light and one dark value each.
enum Palette {
${lines.join('\n')}
}

extension ShapeStyle where Self == Color {
${styles.join('\n')}
}
`;
}

if (import.meta.main) {
	const next = generate(readFileSync(cssPath, 'utf8'));
	const current = (() => {
		try {
			return readFileSync(outPath, 'utf8');
		} catch {
			return '';
		}
	})();
	if (process.argv.includes('--check')) {
		if (current !== next) {
			console.error('Sources/App/Theme/Tokens.swift is stale. Run `bun scripts/tokens.ts` in app-ios and commit it.');
			process.exit(1);
		}
		console.log('Tokens.swift is fresh.');
	} else {
		writeFileSync(outPath, next);
		console.log(`Wrote ${outPath}`);
	}
}
