#!/usr/bin/env bun
// Generates Sources/App/Theme/Tokens.swift and the AccentColor asset from the web's color tokens in app-web/src/index.css.
// `--check` fails instead of writing when the committed file is stale.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const root = resolve(import.meta.dir, '..');
const cssPath = resolve(root, '../app-web/src/index.css');

type Rgba = [number, number, number, number];
type Tokens = Record<string, string>;

function block(css: string, selector: string): Tokens {
	const start = css.indexOf(`\n${selector} {`);
	if (start < 0) throw new Error(`index.css has no ${selector} block`);
	const body = css.slice(start, css.indexOf('\n}', start));
	return Object.fromEntries(
		[...body.matchAll(/(--[\w-]+):\s*([^;]+);/g)].map(([, name, value]) => [name!, value!.trim()]),
	);
}

function color(tokens: Tokens, value: string): Rgba | undefined {
	const reference = value.match(/^var\((--[\w-]+)\)$/);
	if (reference) {
		const target = tokens[reference[1]!];
		if (target === undefined) throw new Error(`Unknown token ${reference[1]}`);
		return color(tokens, target);
	}
	const hex = value.match(/^#([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$/i);
	if (hex) return [...hex.slice(1, 4).map(h => parseInt(h, 16)), 1] as Rgba;
	const rgb = value.match(/^rgb\((\d+) (\d+) (\d+)(?: \/ ([\d.]+))?\)$/);
	if (rgb) return [Number(rgb[1]), Number(rgb[2]), Number(rgb[3]), rgb[4] ? Number(rgb[4]) : 1];
	return undefined;
}

/** `--color-on-accent` and `--glass-strong-bg` become `onAccent` and `glassStrongBg`. */
const swiftName = (token: string) =>
	token.replace(/^--(color-)?/, '').replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());

const literal = ([r, g, b, a]: Rgba) => {
	const hex = `0x${[r, g, b].map(c => c.toString(16).padStart(2, '0').toUpperCase()).join('')}`;
	return a === 1 ? `SRGB(${hex})` : `SRGB(${hex}, ${a})`;
};

/** An asset catalog color with the token's light and dark values. */
const colorset = (lightValue: Rgba, darkValue: Rgba) => {
	const entry = ([r, g, b, a]: Rgba) => ({
		'color-space': 'srgb',
		components: {
			alpha: a.toFixed(3),
			blue: `0x${b.toString(16).padStart(2, '0').toUpperCase()}`,
			green: `0x${g.toString(16).padStart(2, '0').toUpperCase()}`,
			red: `0x${r.toString(16).padStart(2, '0').toUpperCase()}`,
		},
	});
	const colors = [
		{ color: entry(lightValue), idiom: 'universal' },
		{ appearances: [{ appearance: 'luminosity', value: 'dark' }], color: entry(darkValue), idiom: 'universal' },
	];
	return `${JSON.stringify({ colors, info: { author: 'xcode', version: 1 } }, null, '\t')}\n`;
};

/** Every generated file, keyed by its path under `app-ios/`. */
function generate(css: string): Record<string, string> {
	const light = { ...block(css, '@theme'), ...block(css, ':root') };
	const dark = { ...light, ...block(css, ":root[data-theme='dark']") };
	const names = Object.keys(light).filter(name => color(light, light[name]!));
	const lines = names.map(name => {
		const pair = `light: ${literal(color(light, light[name]!)!)}, dark: ${literal(color(dark, dark[name]!)!)}`;
		return `    static let ${swiftName(name)} = Color(${pair})`;
	});
	const styles = names.map(name => `    static var ${swiftName(name)}: Color { Palette.${swiftName(name)} }`);
	const tokens = `// Generated by scripts/tokens.ts from app-web/src/index.css. Do not edit; run \`bun scripts/tokens.ts\`.
import SwiftUI

/// The web's semantic color tokens, one light and one dark value each.
enum Palette {
${lines.join('\n')}
}

extension ShapeStyle where Self == Color {
${styles.join('\n')}
}
`;
	// The app-wide accent, which system chrome such as toolbar buttons in sheets uses instead of SwiftUI's `tint`.
	const accent = colorset(color(light, 'var(--color-accent)')!, color(dark, 'var(--color-accent)')!);
	return {
		'Sources/App/Theme/Tokens.swift': tokens,
		'Sources/App/Assets.xcassets/Contents.json': `${JSON.stringify({ info: { author: 'xcode', version: 1 } }, null, '\t')}\n`,
		'Sources/App/Assets.xcassets/AccentColor.colorset/Contents.json': accent,
	};
}

if (import.meta.main) {
	const files = generate(readFileSync(cssPath, 'utf8'));
	const read = (path: string) => {
		try {
			return readFileSync(resolve(root, path), 'utf8');
		} catch {
			return undefined;
		}
	};
	const stale = Object.keys(files).filter(path => read(path) !== files[path]);
	if (process.argv.includes('--check')) {
		if (stale.length) {
			console.error(`Stale: ${stale.join(', ')}. Run \`bun scripts/tokens.ts\` in app-ios and commit the result.`);
			process.exit(1);
		}
		console.log('Generated colors are fresh.');
	} else {
		for (const [path, contents] of Object.entries(files)) {
			mkdirSync(dirname(resolve(root, path)), { recursive: true });
			writeFileSync(resolve(root, path), contents);
		}
		console.log(`Wrote ${Object.keys(files).join(', ')}`);
	}
}
