// env-manager: procrastimate | 2026-10-08T13:16:37.298Z
// env-manager target: server
// env-manager root: ../..
// env-manager env: local
// AUTO-GENERATED by `env-manager generate` - do not edit
import { z } from 'zod';

const env = z.object({
  API_PORT: z.coerce.number().int().min(1).max(65535),
}).parse(process.env);

export default env;
